/* ====================================================
   Language Dictionary – English & Sinhala
   ==================================================== */
const LANG = {
  en: {
    // Auth
    app_name: "St Johns Monaragala",
    login: "Login",
    register: "Register",
    email: "Email",
    password: "Password",
    name: "Full Name",
    login_btn: "Sign In",
    register_btn: "Create Account",
    login_subtitle: "Welcome back! Sign in to continue.",
    register_subtitle: "Join your class – it's quick and easy.",
    no_account: "Don't have an account?",
    have_account: "Already have an account?",

    // Student
    student_dashboard: "My Availability",
    student_greeting: "Mark your free days for the week",
    week: "Week",
    save: "Save Availability",
    saving: "Saving...",
    saved_success: "Availability saved! ✓",
    my_history: "My History",
    free: "Free",
    busy: "Busy",
    click_to_toggle: "Click to toggle",
    no_data: "No data for this week yet.",

    // Days
    mon: "Mon",
    tue: "Tue",
    wed: "Wed",
    thu: "Thu",
    fri: "Fri",
    sat: "Sat",
    sun: "Sun",
    monday: "Monday",
    tuesday: "Tuesday",
    wednesday: "Wednesday",
    thursday: "Thursday",
    friday: "Friday",
    saturday: "Saturday",
    sunday: "Sunday",

    // Admin
    admin_dashboard: "Admin Dashboard",
    admin_greeting: "Manage your class availability",
    weekly_view: "Weekly View",
    best_day: "Best Day",
    yearly_view: "Yearly View",
    students_list: "Students",
    student_name: "Student",
    total_students: "Total Students",
    responded: "Responded",
    free_count: "Free",
    availability_rate: "Availability Rate",
    best_day_title: "Best Day for Class",
    best_day_desc: "students are free on this day",
    no_students: "No students registered yet.",
    no_responses: "No responses for this week.",
    year: "Year",
    less: "Less",
    more: "More",
    joined: "Joined",
    overview: "Overview",
    details: "Details",

    // General
    logout: "Logout",
    dark_mode: "Dark Mode",
    light_mode: "Light Mode",
    language: "Language",
    loading: "Loading...",
    error: "Something went wrong",
    of: "of",
    settings: "Settings",
    preferences: "Preferences",
    theme: "Theme",
    app_preferences: "App preferences and options",

    // Biometric
    biometric_login: "\ud83d\udd10 Biometric Login",
    enable: "Enable",
    enabled: "Enabled",
    biometric_enabled: "Biometric login enabled! \u2705",
    biometric_disabled: "Biometric login disabled",
    biometric_failed: "Biometric verification failed",
  },

  si: {
    // Auth
    app_name: "St Johns Monaragala",
    login: "පිවිසෙන්න",
    register: "ලියාපදිංචිය",
    email: "ඊමේල්",
    password: "මුරපදය",
    name: "සම්පූර්ණ නම",
    login_btn: "පිවිසෙන්න",
    register_btn: "ගිණුම සාදන්න",
    login_subtitle: "නැවත සාදරයෙන් පිළිගනිමු!",
    register_subtitle: "ඔබේ පන්තියට සම්බන්ධ වන්න.",
    no_account: "ගිණුමක් නැද්ද?",
    have_account: "ගිණුමක් තිබේද?",

    // Student
    student_dashboard: "මගේ තිබෙන දින",
    student_greeting: "සතියේ නිදහස් දින සලකුණු කරන්න",
    week: "සතිය",
    save: "සුරකින්න",
    saving: "සුරැකෙමින්...",
    saved_success: "සුරැකුණි! ✓",
    my_history: "මගේ ඉතිහාසය",
    free: "නිදහස්",
    busy: "කාර්යබහුල",
    click_to_toggle: "මාරු කිරීමට ක්ලික් කරන්න",
    no_data: "මෙම සතිය සඳහා දත්ත නැත.",

    // Days
    mon: "සඳු",
    tue: "අඟ",
    wed: "බදා",
    thu: "බ්‍රහ",
    fri: "සිකු",
    sat: "සෙන",
    sun: "ඉරි",
    monday: "සඳුදා",
    tuesday: "අඟහරුවාදා",
    wednesday: "බදාදා",
    thursday: "බ්‍රහස්පතින්දා",
    friday: "සිකුරාදා",
    saturday: "සෙනසුරාදා",
    sunday: "ඉරිදා",

    // Admin
    admin_dashboard: "පරිපාලක උපකරණ පුවරුව",
    admin_greeting: "පන්ති ලබාගත හැකි බව කළමනාකරණය කරන්න",
    weekly_view: "සතිපතා දැක්ම",
    best_day: "හොඳම දිනය",
    yearly_view: "වාර්ෂික දැක්ම",
    students_list: "සිසුන්",
    student_name: "සිසුවා",
    total_students: "මුළු සිසුන්",
    responded: "ප්‍රතිචාර",
    free_count: "නිදහස්",
    availability_rate: "නිදහස් අනුපාතය",
    best_day_title: "පන්තියට හොඳම දිනය",
    best_day_desc: "සිසුන් මෙම දිනයේ නිදහස්",
    no_students: "තවම සිසුන් ලියාපදිංචි වී නැත.",
    no_responses: "මෙම සතිය සඳහා ප්‍රතිචාර නැත.",
    year: "වර්ෂය",
    less: "අඩු",
    more: "වැඩි",
    joined: "සම්බන්ධ වූ",
    overview: "දළ විශ්ලේෂණය",
    details: "විස්තර",

    // General
    logout: "පිටවීම",
    dark_mode: "අඳුරු ප්‍රකාරය",
    light_mode: "ආලෝක ප්‍රකාරය",
    language: "භාෂාව",
    loading: "පූරණය වෙමින්...",
    error: "යමක් වැරදුණි",
    of: "න්",

    // Biometric
    biometric_login: "🔐 ජීව මිතික පිවිසුම",
    enable: "සක්‍රීය කරන්න",
    enabled: "සක්‍රීයයි",
    biometric_enabled: "ජීව මිතික පිවිසුම සක්‍රීය කර ඇත! ✅",
    biometric_disabled: "ජීව මිතික පිවිසුම අශක්‍රීය කර ඇත",
    biometric_failed: "ජීව මිතික හිරිහැණඨීම අසාර්ථකයි",
  }
};

// Expose globally
window.LANG = LANG;
